# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

# EventBridge
aws.eventBridge.bus=${AWS_EVENTBRIDGE_BUS}

# S3
aws.s3.bucket=${AWS_S3_BUCKET:local-bucket}
aws.region=${AWS_REGION:eu-west-3}
